-- Run this once in Supabase -> SQL Editor.
create table if not exists public.scores (
  id bigint generated by default as identity primary key,
  player_name varchar(24) not null,
  score smallint not null check (score between 0 and 100),
  deadlines smallint not null check (deadlines between 0 and 25),
  prioritization smallint not null check (prioritization between 0 and 25),
  planning smallint not null check (planning between 0 and 25),
  adaptability smallint not null check (adaptability between 0 and 25),
  created_at timestamptz not null default now(),
  constraint score_parts_match check (deadlines + prioritization + planning + adaptability = score)
);

create index if not exists scores_ranking_idx
  on public.scores (score desc, created_at asc);

-- The browser never talks directly to Supabase in this project.
-- Keep RLS enabled and do not create public insert/select policies.
alter table public.scores enable row level security;
